# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [desarrollo, pruebas]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Iniciar proceso instalación
        run: |
          sh ~/clearOne/clearOne.sh | true
          echo sa | sudo -S  dpkg --add-architecture i386
          echo sa | sudo -S  apt update -y
          echo sa | sudo -S  apt upgrade -y
          echo sa | sudo -S  apt-get update -y
          echo sa | sudo -S  apt-get upgrade -y
          echo sa | sudo -S  apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 -y
          killall tocGame | true
          killall lanzadera.sh | true
          echo sa | sudo -S rm -rf ~/inicioGnome/  ~/tocGame/ ~/updater/ ~/clearOne/ ~/instaladorBeta.* ~/instalador.zip.* ~/instalador.zip ~/instalador/ ~/tocGameFunciona/ ~/tocGameTemporal/ ~/tocGameScripts/
          echo sa | sudo -S  apt install git -y
          cd ~
          git clone --depth 1 https://github.com/dobleamarilla/instalador.git
          cd instalador
          cp -f -r clearOne ~
          cp -f -r updater ~
          wget http://silema.hiterp.com/instalador/binariosToc.zip
          unzip binariosToc.zip
          cp -f -r tocGame ~
          cp -f -r tocGame/scripts ~/tocGame
          echo sa | sudo -S  cp inicioGnome/clearOne.desktop /etc/xdg/autostart
          echo sa | sudo -S  cp inicioGnome/lanzadera.desktop /etc/xdg/autostart
          echo sa | sudo -S  chmod a+x ~/tocGame/tocGame
          echo sa | sudo -S  chmod a+x ~/tocGame/scripts/lanzadera.sh
          echo sa | sudo -S  chmod a+x ~/tocGame/scripts/permisos.sh
          echo sa | sudo -S  chmod a+x ~/tocGame/scripts/starttoc.sh
          echo sa | sudo -S  chmod a+x ~/tocGame/scripts/minivpn.sh
          echo sa | sudo -S  chmod a+x ~/tocGame/scripts/borrarMongo.sh
          echo sa | sudo -S  chmod a+x ~/tocGame/scripts/borrarDatabase.sh
          echo sa | sudo -S  chmod a+x ~/updater/tocGameUpdater.sh
          echo sa | sudo -S  chmod a+x ~/clearOne/clearOne.sh
          echo sa | sudo -S  chmod a+x ~/clearOne/CoLinux
          echo sa | sudo -S  chmod a+x ~/clearOne/kill_ipcs.sh
          echo sa | sudo -S  chmod a+x ~/clearOne/kil_sema.sh
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo systemctl start mongod
          sudo systemctl daemon-reload
          sudo systemctl enable mongod
          echo sa | sudo -S rm -rf ~/instalador/ ~/instalador.sh
          reboot